spring.application.name=DietiEstates25-BackEnd
spring.datasource.url=jdbc:postgresql://postgres:5432/DietiEstates25
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

file.upload.directory=uploads/foto_immobili
spring.mvc.static-path-pattern=/uploads/foto_immobili/**
spring.web.resources.static-locations=file:${file.upload.directory}
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=12MB

logging.level.com.dietiestates25backend=DEBUG

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.boot.autoconfigure.jdbc=TRACE

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5970
jwt.expiration=3600000

# Google
spring.security.oauth2.client.registration.google.client-id=178222475143-0au38na2qlf7hqph20udkis3q1itm2k3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# Facebook
spring.security.oauth2.client.registration.facebook.client-id=1036595351815886
spring.security.oauth2.client.registration.facebook.client-secret=6861c6eaf35bcd41096e3000a198084b
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/login/oauth2/code/facebook
spring.security.oauth2.client.registration.facebook.scope=email,public_profile

# GitHub
spring.security.oauth2.client.registration.github.client-id=Ov23liaZ0ZDfkqJhV087
spring.security.oauth2.client.registration.github.client-secret=5945cf82c6ccfcb39e697e5859c8943285205d7e
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github
spring.security.oauth2.client.registration.github.scope=user:email

#Base URL
baseUrl = http://localhost:8080

server.port=8080

server.servlet.session.cookie.domain=localhost
server.servlet.session.cookie.path=/